### PR TITLE
Bump to latest parent pom to get RequireUpperBoundDeps checks

### PR DESCRIPTION
**Pull request by batmat**
Filed this hoping it would possibly reveal more clearly some incompatibilities to help https://github.com/jenkinsci/bouncycastle-api-plugin/pull/19 move forward, but apparently no.

So filing it since this would need to be done at some point anyway.

@reviewbybees esp. @alvarolobato as the maintainer

### CODE REVIEW

**Comment by jglick** [comment]
Need to create a `Jenkinsfile` I suppose.

**Comment by batmat** [comment]
@jglick https://github.com/jenkinsci/bouncycastle-api-plugin/pull/21

**Comment by batmat** [comment]
@reviewbybees done.

**Comment by batmat** [comment]
ci.jenkins.io is down for unplanned maintenance, waiting for the PR build to kick in.

**Pull request merged**
