### PR TITLE
Modernize to Jenkins 2.440.3

### PR DESCRIPTION
**Pull request by sghill-rewrite**
Hi!

This PR aims to move this plugin to the [recommended](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) Jenkins baseline version.

If there are additional requirements for accepting PRs - such as additional lag time before adopting a baseline - feel free to reply in the comments.

## Testing done
Ran `mvn clean verify`.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

Refs: sghill-rewrite/campaigns#4

Closes #157 

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.jenkins.ModernizePlugin?organizationId=SmVua2lucyBDSQ%3D%3D

### CODE REVIEW

**Comment by jtnord** [comment]
The recommendations are for new plugins. they explicitly state different criteria for updating the baseline.

> There are [statistics of core versions by plugin](https://stats.jenkins.io/pluginversions/) that can help you decide. These are updated monthly. When updating the core dependency, choose the [newest LTS version](https://www.jenkins.io/changelog-stable/) that doesn’t exclude a majority of your existing users (by requiring a newer Jenkins than they have).

As the stats are currently bogus it is impossible to know what the majority of current users are using.

This plugin does not need to use any new APIs from the newer Jenkins core, nor from the PR need adapting to any newer core deprecation, and is tested as part of the OSS bom. So this appears to be potentially just locking out older Jenkins users for no actual gain as far as I can tell?  Additionally the baseline currently in use does not drag in any detached plugins

**Comment by sghill** [comment]
Thanks! Do you have a policy we can codify?

**Comment by jotradovec-r7** [comment]
Is this plugin also affected by https://www.jenkins.io/security/advisory/2024-08-07/ because of the unsupported jenkins.version ?

**Comment by jtnord** [comment]
Obsolete by #161

**Pull request closed without merging**
